### ISSUE TITLE
Is this project still alive ?

### ISSUE THREAD

**Issue by uffejakobsen** [74hc595/chipdb#3]
Hi,

Is this project still alive ?

Will you accept changes/additions

Thanks :-)

**Comment by DarkLuk42** [comment]
@uffejakobsen
I asked Matt Sarnoff at [Twitter](https://twitter.com/txsector) and he answered:
> It's not updated often, but I still accept PRs. I'm on vacation until the end of the month though.

**Comment by 74hc595** [comment]
@uffejakobsen The project is alive but in maintenance mode. I will still accept pull requests for new part definitions.
